export default function PrivacyPage() {
  return (
    <div className="grid" style={{ gap: 24 }}>
      <section className="card">
        <h1>Privacy Policy</h1>
        <p className="small">Last updated: March 2026</p>
        <p>
          MathSupport AI is currently offered as a free beta product. This Privacy Policy explains
          what information we collect, how we use it, and how we protect it.
        </p>
      </section>

      <section className="card">
        <h2>Information we collect</h2>
        <p>
          We may collect the email address you provide, the questions you submit, the tutor
          responses generated by the system, and limited technical information such as request
          metadata used for security, diagnostics, and beta usage limits.
        </p>
      </section>

      <section className="card">
        <h2>How we use your information</h2>
        <p>
          We use submitted information to operate the tutor, save session history, improve the
          product, understand beta usage, reduce abuse, and shape future features.
        </p>
      </section>

      <section className="card">
        <h2>AI-generated responses</h2>
        <p>
          Tutor responses are generated by artificial intelligence and may occasionally be incorrect,
          incomplete, or inappropriate for your exact academic setting. You should verify important
          results before relying on them.
        </p>
      </section>

      <section className="card">
        <h2>Data sharing</h2>
        <p>
          We do not sell your personal information. We may use third-party infrastructure providers
          to operate the product, including hosting, database, and AI services that process data on
          our behalf in order to provide the service.
        </p>
      </section>

      <section className="card">
        <h2>Data retention</h2>
        <p>
          We may retain beta submissions, session history, and signup information for product
          development, debugging, analytics, and future service improvement unless deletion is
          requested and technically feasible.
        </p>
      </section>

      <section className="card">
        <h2>Children and student use</h2>
        <p>
          If this service is used by minors or students, a parent, guardian, teacher, or school
          should review whether the tool is appropriate for that use. This beta is not currently
          designed as a formal school records system.
        </p>
      </section>

      <section className="card">
        <h2>Contact</h2>
        <p>
          For privacy-related questions or deletion requests, please contact us through the contact
          method that will be listed on the site as the beta expands.
        </p>
      </section>
    </div>
  );
}